use_frameworks!

platform :ios, '8.0'

target 'AGNetwork_Example' do
  pod 'AGNetwork', :path => '../'

  target 'AGNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
