use_frameworks!

platform :ios, '8.0'

target 'AGNetwork_Example' do
  pod 'AGNetwork', :path => '../'
  pod 'FMDB'
  pod 'MJExtension'
  pod 'AFNetworking'

  target 'AGNetwork_Tests' do
    inherit! :search_paths
    
#    pod 'FBSnapshotTestCase'
  end
end
